# Generated by Django 5.1.7 on 2025-04-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='articles_per_page',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='breaking_news_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='default_sort',
            field=models.CharField(choices=[('newest', 'Newest First'), ('relevance', 'Most Relevant'), ('popularity', 'Most Popular')], default='newest', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
