# Generated by Django 5.1.7 on 2025-04-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_userpreference_articles_per_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='articles_per_page',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='breaking_news_alerts',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='default_sort',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='email_notifications',
        ),
    ]
